addr = "127.0.0.1:9000"

[[http]]
addr = ":3000"

[[http.routes]]
path = "POST /init"
service = "init_configuration"

[[http.routes]]
path = "GET /files"
service = "list_nix_files"

[[http.routes]]
path = "GET /contents"
service = "get_nix_contents"

[[http.routes]]
path = "POST /contents"
service = "set_nix_contents"

[[http.routes]]
path = "POST /dry-build"
service = "run_dry_build"

[[http.routes]]
path = "POST /test"
service = "run_test"

[[http.routes]]
path = "POST /switch"
service = "run_switch"

[[http.routes]]
path = "GET /health"
service = "liveness_check"

[[http.routes]]
path = "GET /fetch"
service = "fetch_local_url"

[[http.routes]]
path = "GET /ws/ssh"
service = "ssh"
websocket = true

[[http.routes]]
path = "GET /text"
service = "text_liveness"
